### ISSUE TITLE
Discussion Topics on Common Repos

### ISSUE THREAD

**Issue by cdnicoll** [ocupop/4p-common#2]
- [ ] What should directory structure look like
- [ ] How should we handle documentation
  - [ ] Do we want a `documentation/` directory that will provide examples for each component, or should we relay on the `example/` directory to provide the samples
- [ ] Right now using npm everything is public, assuming this will be okay moving forward

**Comment by cdnicoll** [comment]
When we import we're importing something that looks like this:
```js
import {
  TextInput,
  TextArea,
  SwitchInput,
  SelectInput,
  CreateSelect,
  FooBarComponent,
  BarFooComponent
} from '@ocupop/4p-common'
```

Do we want everything on this level or do we want to come up with some hiarchy when importing, for example:

```js
import {
  forms {
    TextInput,
    TextArea,
    SwitchInput,
    SelectInput,
    CreateSelect
  }
  FooBarComponent,
  BarFooComponent
} from '@ocupop/4p-common'
```

**Comment by tbeck** [comment]
@cdnicoll - I think that in this case we can keep everything top level for now.
