### ISSUE TITLE
Add Skeleton UI to common form fields

### ISSUE THREAD

**Issue by sethburtonhall** [ocupop/4p-common#4]
https://github.com/dvtng/react-loading-skeleton

**Comment by tbeck** [comment]
@sethburtonhall - From what I saw, this is in a good spot. Are there additional changes that you want to make before we review/close?

I am assuming that further evolution of the Skeleton UI patterns you have introduced would warrant adding new issues.

**Comment by sethburtonhall** [comment]
I think we are good to integrate Skeleton UI as one of the final steps of our component workflow, after the design feedback is complete and components are developed. Not sure specific Skeleton issues are required since it will be part of component design as a whole.
